"""Create a baseline migrations

Revision ID: 72619085b09f
Revises: 
Create Date: 2023-09-29 15:14:31.497694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72619085b09f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=False)
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('player',
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('last_daily', sa.DateTime(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_index(op.f('ix_player_discord_id'), 'player', ['discord_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_table('card_has_tags',
    sa.Column('card', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('card', 'tag')
    )
    op.create_table('card_upgrade',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'requirement_id')
    )
    op.create_index(op.f('ix_card_upgrade_card_id'), 'card_upgrade', ['card_id'], unique=False)
    op.create_table('event_has_cards',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('card', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event', 'card')
    )
    op.create_table('player_has_cards',
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('card', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['player'], ['player.discord_id'], ),
    sa.PrimaryKeyConstraint('player', 'card', 'amount')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_has_cards')
    op.drop_table('event_has_cards')
    op.drop_index(op.f('ix_card_upgrade_card_id'), table_name='card_upgrade')
    op.drop_table('card_upgrade')
    op.drop_table('card_has_tags')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_player_discord_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
